osx_image: xcode7.1
language: objective-c
podfile: Demo/Podfile

env:
  global:
    - LANG=en_US.UTF-8
    - COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=true

cache:
  - bundler
  - cocoapods

script:
  - rake test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sleep 5
